version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
      POSTGRES_DB: appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  python_app:
    build: ./app
    container_name: python_app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://appuser:apppassword@db:5432/appdb
    command: python main.py

  frontend:
    build: ./antigraviti_react
    container_name: react_frontend
    ports:
      - "8080:80"
    depends_on:
      - python_app

volumes:
  postgres_data:
