apiVersion: batch/v1
kind: Job
metadata:
  name: dbsetup-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: dbsetup
          image: python-app:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args: ["opentelemetry-instrument python3 dbSetup.py"]
          env:
            - name: DB_NAME
              value: "appdb"
            - name: DB_USER
              value: "appuser"
            - name: DB_PASSWORD
              value: "apppassword"
            - name: DB_HOST
              value: "db"
            - name: DB_PORT
              value: "5432"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=dbsetup-job"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://host.docker.internal:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
